CREATE TABLE users (
    userID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE videoGames (
    gameID INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(80) NOT NULL,
    description VARCHAR(255),
    is_completed BOOLEAN DEFAULT FALSE,
    userID INT NOT NULL,
    FOREIGN KEY (userID) REFERENCES lists(userID)
);